clubEarth/clubEarth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from earth.views import login, logout, login_page

# Import URLs from earth app
from earth.urls import urlpatterns as earth_urls

urlpatterns = [
    url(r'^', include(earth_urls, namespace="earth")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout, name="logout"),
    url(r'^login_page/$', login_page, name="login_page"),
]

clubEarth/earth/urls.py
from django.conf.urls import url

from earth.views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^home$', home, name='home'),
    url(r'^event/list$', events, name='events'),
    url(r'^event/(?P<event_id>\d+)$', event_info, name="event_info"),
    url(r'^forums/(?P<category_id>\d+)$', forum_category, name="forum_category"),
    url(r'^thread/(?P<thread_id>\d+)$', thread_info, name="thread_info"),
    url(r'^news/list$', news, name='news'),
    url(r'^forums/$', forums, name='forums'),
    url(r'^event/create$', create_event, name='create_event'),
]

clubEarth/earth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.username

class Event(models.Model):
    name = models.CharField(max_length=80, null=False, blank=False)
    host = models.ForeignKey(Profile, null=True, blank=True)
    description = models.CharField(max_length=400, default="")
    location1 = models.CharField(max_length=400, default="")
    location2 = models.CharField(max_length=400, default="")
    date = models.CharField(max_length=400, default="")
    start_time = models.CharField(max_length=400, default="")
    end_time = models.CharField(max_length=400, default="")

    def __str__(self):
        return self.name

class Attending(models.Model):
    person = models.ForeignKey(Profile)
    event = models.ForeignKey(Event)

    def __str__(self):
        return "%s is attending %s" % (self.person.user.username, self.event)

class Category(models.Model):
    name = models.CharField(max_length=20, null=False, blank=False)
    description = models.CharField(max_length=140, null=True, blank=True)

    def __str__(self):
        return self.name

class Thread(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=80, null=False, blank=False)
    content = models.CharField(max_length=1000, null=True, blank=True)
    author = models.ForeignKey(Profile, null=True, blank=True)
    date = models.DateField(default=timezone.now())

    def __str__(self):
        return "Title: %s" % self.title

class Comment(models.Model):
    content = models.CharField(max_length=400, null=False, blank=False)
    author = models.ForeignKey(Profile, null=True, blank=True)
    date = models.DateField(default=timezone.now())
    thread = models.ForeignKey(Thread, null=True, blank=True)

    def __str__(self):
        return "Content: %s" % self.content

class EventComment(models.Model):
    author = models.ForeignKey(Profile)
    body = models.CharField(max_length=400, null=False, blank=False)
    event = models.ForeignKey(Event)

    def __str__(self):
        return self.body

class Article(models.Model):
    title = models.CharField(max_length=400)
    url = models.CharField(max_length=400)
    content = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

clubEarth/earth/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ProfileForm(forms.ModelForm):

	class Meta:
		model = Profile
		exclude = ('user', )

class UserForm(UserCreationForm):
	username = forms.CharField(label="Username", required=True, 
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username', }))
	password1 = forms.CharField(label="Password", required=True,
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
	password2 = forms.CharField(label="Confirm_Password", required=True,
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
	email = forms.EmailField(label='Email', required=True, 
		widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))

	class Meta:
		model = User
		fields= ["username", "password1", "password2", "email"]

class ThreadForm(forms.ModelForm):
	title = forms.CharField(label="Title", required=True, 
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title', }))
	content = forms.CharField(label="Content", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Content', }))

	class Meta:
		model = Thread
		fields = ["title", "content"]

class CommentForm(forms.ModelForm):
	content = forms.CharField(label="Content", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment', }))

	class Meta:
		model = Comment
		fields = ["content"]

class EventForm(forms.ModelForm):
	name = forms.CharField(label="Event Name", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}))
	description = forms.CharField(label="Description", required=True, 
		widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '4', 'placeholder': 'Description'}))
	location1 = forms.CharField(label="location1", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address 1'}))
	location2 = forms.CharField(label ="location2", required=False, 
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address 2'}))
	date = forms.CharField(label ="date", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'datepicker', 'placeholder': 'Date'}))
	start_time = forms.CharField(label ="start_time", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Start Time: e.g. 10:00am'}))
	end_time = forms.CharField(label ="end_time", required=True,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'End Time: e.g. 2:00pm'}))

	class Meta:
		model = Event
		fields = ["name", "description", "location1", "location2", "date", "start_time", "end_time"]

clubEarth/earth/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from earth.models import *
from earth.forms import *

# Create your views here.
def index(request):

    if request.user.is_authenticated():
        return redirect("earth:home")

    if request.method == "POST":
        if "email" in request.POST:
            user_form = UserForm(request.POST)
            profile_form = ProfileForm(request.POST)

            if user_form.is_valid():
                django_user = user_form.save()
                profile = profile_form.save(commit=False)
                profile.user = django_user
                profile.save()

                profile_form = ProfileForm()
                user_form = UserForm()

                context = {
                    "user_form": user_form,
                    "profile_form":profile_form,
                    "register_success": True,
                }

                return render(request, "index.html", context)


    user_form = UserForm()
    profile_form = ProfileForm()

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }

    return render(request, "index.html", context)

@login_required
def home(request):

    threads = Thread.objects.all()[:3]
    events = Event.objects.all()[:3]
    articles = Article.objects.all()[:6]


    context = {
        "header": "News_All",
        "threads": threads,
        "events": events,
        "articles": articles,
    }
    return render(request, "home.html", context)

def login_page(request):
    if request.user.is_authenticated():
        return redirect("earth:index")

    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect(request.POST.get('next','earth:index'))
        else:
            context = {
                "login_failed": True,
            }
            return render(request, "login.html", context)

    context = {
        "login_failed": False,
    }
    return render(request, "login.html", context)


def login(request):

    if request.user.is_authenticated():
        return redirect("earth:index")

    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect(request.POST.get('next','earth:index'))
        else:
            context = {
                "login_failed": True,
                "user_form": UserForm(),
                "profile_form": ProfileForm(),
            }
            return render(request, "index.html", context)

    return render(request, "index.html")

def logout(request):

    if request.user.is_authenticated():
        auth.logout(request)
        return redirect("earth:index")
    else:
        return redirect("earth:index")

def events(request):
    context = {
        'events': Event.objects.all(),
        'header': "Events_All",
    }

    if request.method == "POST" and "create_event" in request.POST:
        new_event = Event.objects.create(name="Untitled Event", 
                                         host=request.user.profile, 
                                         description="Description of your event.",
                                         location1="101 Example St.",
                                         location2="West Henrietta, NY 14586")
        new_event.save()

        attender = Attending.objects.create(event=new_event, person=request.user.profile)
        attender.save()

        return redirect("earth:event_info", event_id=new_event.id)

    return render(request, "event_list.html", context)

def news(request):
    context = {
        #'news': News.objects.all(),
        'header': "News_All",
    }
    return render(request, "news_list.html", context)

def forums(request):
    context = {
        'categories': Category.objects.all(),
        'header': "Forums_All",
    }
    return render(request, "forums.html", context)

def forum_category(request, category_id=0):
    category = get_object_or_404(Category, pk=category_id)
    threads = Thread.objects.filter(category=category)

    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        if thread_form.is_valid():
            thread = thread_form.save(commit=False)
            thread.category = category
            thread.author = request.user.profile
            thread.save()
            context = {
                'category': category,
                'threads': Thread.objects.filter(category=category),
                'header': "Forums_All",
                'success': True,
                'thread_form': thread_form,

            }

            return render( request, "forum_category.html", context)

    thread_form = ThreadForm()
    context = {
        'category': category,
        'threads': threads,
        'header': "Forums_All",
        'thread_form': thread_form,
    }

    return render(request, "forum_category.html", context)

def thread_info(request, thread_id=0):
    thread = get_object_or_404(Thread, pk=thread_id)
    comments = Comment.objects.filter(thread=thread)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.thread = thread
            comment.author = request.user.profile
            comment.save()
            context = {
                'thread': thread,
                'comments': Comment.objects.filter(thread=thread),
                'header': "Forums_ALL",
                'success': True,
                'comment_form': comment_form,
            }

            return render(request, "thread_info.html", context)

    comment_form = CommentForm()   
    context = {
        'thread': thread,
        'comments': comments,
        'header': "Forums_All",
        'comment_form': comment_form,
    }

    return render(request, "thread_info.html", context)

@login_required
def create_event(request):
    my_user = request.user.profile

    if request.method == "POST":
        create_event_form = EventForm(request.POST)
        event = create_event_form.save(commit=False)
        event.host = my_user
        event.save()

        attender = Attending.objects.create(event=event, person=my_user)
        attender.save()

        attendees = Attending.objects.filter(event__id=event.id)
        attendee_count = attendees.count

        comments = EventComment.objects.filter(event__id=event.id)

        context = {
            'event': event,
            'header': "Events_All",
            'my_user': my_user,
            'attendees': attendees,
            'attendee_count': attendee_count,
            'comments': comments
         }
        return render(request, "event_info.html", context)

    create_event_form = EventForm()
    context = {
        'event_form': create_event_form,
        'my_user': my_user
    }
    return render(request, "create_event.html", context)

@login_required
def event_info(request, event_id=0):
    event = get_object_or_404(Event, pk=event_id)
    my_user = request.user.profile

    attendees = Attending.objects.filter(event__id=event.id)
    attendee_count = attendees.count

    comments = EventComment.objects.filter(event__id=event.id)

    context = {
        'event': event,
        'header': "Events_All",
        'my_user': my_user,
        'attendees': attendees,
        'attendee_count': attendee_count,
        'comments': comments
    }

    if request.user.is_authenticated():
        if request.method == 'POST' and 'submit_event_edit' in request.POST:
            event_name = request.POST['name']
            event_description = request.POST['description']
            event_location1 = request.POST['location1']
            event_location2 = request.POST['location2']
            event_date = request.POST['date']
            event_start = request.POST['start_time']
            event_end = request.POST['end_time']

            event.name = event_name
            event.description = event_description
            event.location1 = event_location1
            event.location2 = event_location2
            event.date = event_date
            event.start_time = event_start
            event.end_time = event_end
            event.save()

            return redirect("earth:event_info", event_id=event.id)
        elif request.method == 'POST' and 'cancel_event_edit' in request.POST:
            return redirect("earth:event_info", event_id=event.id)

        elif request.method == 'POST' and 'attend_event' in request.POST:    
            attender = Attending.objects.create(event=event, person=request.user.profile)
            attender.save()
            
            return redirect("earth:event_info", event_id=event.id)

        elif request.method == 'POST' and 'create_event_comment' in request.POST:
            event_comment = request.POST['comment']

            comment = EventComment.objects.create(event=event, author=request.user.profile, body=event_comment)
            comment.save()


    return render(request, "event_info.html", context)

clubEarth/earth/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}ClubEarth{% endblock title %}</title>
        <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/static/earth/css/earth.css" />
        <link rel="stylesheet" type="text/css" href="/static/earth/css/event_list.css" />
        <link rel="stylesheet" type="text/css" href="/static/earth/css/fonts.css" />
        <link rel="stylesheet" type="text/css" href="/static/earth/css/create_event.css" />
        <script src="/static/jquery-1.11.2.min.js"></script>
        <script src="/static/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    </head>

    <body>
      <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> 
          <a href="{% url 'earth:index' %}">
            <img class="nav-logo" src="/static/images/ClubEarthLogo_Green.png" style="width:50px;height:50px;display:inline-block;float:left;" />
            <div class="navbar-brand">ClubEarth</div>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li {% if header == "News_All" %} class="active" {% endif %}><a href="{% url 'earth:home' %}">News</a></li>
            <li {% if header == "Events_All" %} class="active" {% endif %}><a href="{% url 'earth:events' %}">Events</a></li>
            <li {% if header == "Forums_All" %} class="active" {% endif %}><a href="{% url 'earth:forums' %}">Forums</a></li>
            
          </ul>
          {% if request.user.is_authenticated %}
          <form action="{% url 'logout' %}" class="navbar-form navbar-right" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-default">Logout</button>
          </form>
          {% else %}
          <form action="{% url 'login' %}" class="navbar-form navbar-right" method="post">
            {% csrf_token %}
            <div class="form-group {% if login_failed %}has-error{% endif %}">
                {% if login_failed %}
                <label for="username" style="color:white">Login failed</label>
                {% endif %}
                <input type="text" class="form-control" name="username" placeholder="Username">
            </div>
            <div class="form-group {% if login_failed %}has-error{% endif %}">
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Sign In</button>
          </form>
          {% endif %}
          
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
    {% block content %}{% endblock content %}
    </div>

    </body>
</html>

clubEarth/earth/templates/create_event.html
{% extends 'base.html' %}
{% block title %}
Event
{% endblock title %}

{% block content %}

<head>
  <meta charset="utf-8">
  <title>jQuery UI Accordion - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script type"text/javascript">
   $(function() {
    $( "#datepicker" ).datepicker();
  });
  </script>
</head>

<div class="create-event-container">
	<h2 class="create-event-text">Create Event</h2>
        <div class="row row-buffer-bottom">
            <form action={% url 'earth:create_event' %} method="post">
                {% csrf_token %}
                <div class="col-md-5">
	                <div class="form-group">
	                    {{ event_form.name }}
	                </div>
	                <div class="form-group" rows="3">
	                    {{ event_form.description }}
	                </div>
	                <div class="form-group event-date-field">
	                	{{ event_form.date}}
	            	</div>
	            	<div class="form-group event-time-field">
	            		{{ event_form.start_time }}
	            	</div>
	            	<div class="form-group event-time-field">
	            		{{ event_form.end_time }}
	            	</div>
	            </div>
	            <div class="col-md-5">
	            	<div class="form-group">
	                    {{ event_form.location1 }}
	                </div>
					<img src="/static/images/location.png" class="event-map"></img>
	                <div class="form-group">
	                    {{ event_form.location2 }}
	                </div>
	                <button type="submit" class="btn btn-default submit-event">Submit</button>
	            </div>
            </form>
        </div>
    </div>
{% endblock content %}

clubEarth/earth/templates/event_list.html
{% extends 'base.html' %}
{% block title %}
Events
{% endblock title %}
{% block content %}

<head>
  <meta charset="utf-8">
  <title>jQuery UI Accordion - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script type"text/javascript">
  $(function() {
    $( "#accordion" ).accordion();
  });
   $(function() {
    $( "#datepicker" ).datepicker();
  });

   $("#datepicker").on('input', function(){
   		$(".event-card-list").scrollTop -= 100;
   });
  </script>
</head>
<div class="col-md-3 calendar-section">
	<h2>Choose A Date</h2>
		<p>Date: <input type="text" id="datepicker"></p>
	<h2>Your Events</h2>
	<div id="accordion" class="your-events-container">
		<div class="event-status">Going</div>
		<ul class="your-events">
			{% for event in events %}
			<li class="your-event">
				<a class="your-event-name" href="{% url 'earth:event_info' event.id %}">{{ event.name }}</a>
			</li>
			{% endfor %}
		</ul>
		<div class="event-status">Not Going</div>
		<ul class="your-events">
			{% for event in events %}
			<li class="your-event">
				<a class="your-event-name" href="{% url 'earth:event_info' event.id %}">{{ event.name }}</a>
			</li>
			{% endfor %}
		</ul>
		<div class="event-status">Pending</div>
		<ul class="your-events">
			{% for event in events %}
			<li class="your-event">
				<a class="your-event-name" href="{% url 'earth:event_info' event.id %}">{{ event.name }}</a>
			</li>
			{% endfor %}
		</ul>
		<div class="event-status">Hosting</div>
		<ul class="your-events">
			{% for event in events %}
			<li class="your-event">
				<a class="your-event-name" href="{% url 'earth:event_info' event.id %}">{{ event.name }}</a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
<div class="col-md-9 event-list">
	<div class="event-list-top">
		<h1>Events In Your Area</h1>
		<h2 class="area-text">Rochester, NY</h2>
		{% if request.user.is_authenticated %}
		<h2><a class="btn btn-success btn-lg" href="{% url 'earth:create_event' %}">Create Event</a></h2>
		{% endif %}
	</div>
	<div class="event-card-list">
		<div class="event-date-label">October 2015</div>
		{% for event in events %}
		<div class="event-container">
			<div class="event-image-container">
				<img class="event-image" src="http://static1.squarespace.com/static/559bd163e4b01adcb4fa3be4/55b7d23ee4b015b50439b1b2/55b7d34de4b032739413227e/1443973774024/Final+Leaf+Project_Page_3.jpg?format=1000w"></img>
			</div>
			<div class="event-info-container">
				<a class="event-name" href="{% url 'earth:event_info' event.id %}">{{ event.name }}</a>
				<h3 class="event-host">hosted by {{ event.host.user.username }}</h3>
			</div>
			<div class="event-date">10/4/15</div>
		</div> 
		{% endfor %}
	</div>
</div>



{% endblock content %}

clubEarth/earth/templates/forum_category.html
{% extends 'base.html' %}
{% block title %}
{{category.name}}
{% endblock title %}
{% block content %}

<h1>{{ category.name }} <br /> <small>Rochester, NY <i class="fa fa-location-arrow"></i></small></h1>

<script type="text/javascript">
	$('#newthread').on('shown.bs.modal', function () {
	  $('input[name="title"]').focus()
	})
</script>

<div class="col-sm-offset-10 col-sm-2 pull-right"><a data-toggle="modal" data-target="#newthread" class="btn btn-default pull-right">New Thread</a></div>
<br />
<hr />
<ol class="breadcrumb">
	<li><a href="/forums">Forums</a></li>
	<li class="active">{{category.name}}</li>
</ol>

<div class="list-group">
{% for thread in threads %}
<a href="{% url 'earth:thread_info' thread.id %}" class="list-group-item">
<h4 clsas="list-group-item-heading">{{ thread.title }}</h4>
<p class="list-group-item-text">by {{ thread.author }} on {{ thread.date }}</p>
</a>
{% endfor %}
</div>

<div class="modal fade" id="newthread" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Thread Form</h4>
      </div>
      <div class="modal-body">
        <form action="{% url 'earth:forum_category' category.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ thread_form.title }}
        </div>
        <div class="form-group">
            {{ thread_form.content }}
        </div>      	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->





{% endblock content %}

clubEarth/earth/templates/forums.html
{% extends 'base.html' %}
{% block title %}
Forums
{% endblock title %}
{% block content %}
<h1>Forums <br /> <small>Rochester, NY <i class="fa fa-location-arrow"></i></small></h1>
<hr />
<ol class="breadcrumb">
	<li class="active">Forums</li>
</ol>

<div class="list-group">
{% for category in categories %}
<a href="{% url 'earth:forum_category' category.id %}" class="list-group-item">
<h4 class="list-group-item-heading">{{category.name}}</h4>
<p class="list-group-item-text">{{category.description}}</p>
</a>
{% endfor %}
</div>


{% endblock content %}

clubEarth/earth/templates/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}
{% block content %}
<script type="text/javascript">
	$('.container').removeClass("container");
</script>

<div class="col-md-3 userbar col-buffer-right">
	<div class="row">
		<p>
			<i class="fa fa-user fa-2x" style="font-size:34px"></i><span style="font-size:30px;display:inline;"> {{ request.user.username }}</span>
		</p>
		<p style="font-size:20px;">Your rank: <span class="badge" style="font-size:20px;">4</span> </p>
		<p>*Your rank is an indicator of how active you are in your community.<br>
		<br>
			<span style="font-size:16px;">Suggestions to improve rank:</span>
			<ul>
				<li>Attend an Event.</li>
				<li>Post on the Forums.</li>
				<li>Refer friends to ClubEarth</li>
			</ul>
		</p>
		</div>
	<div class="row">
		<h3>Top Activity:</h3>
		<div class="col-sm-12">
			<ul class="list-group">
			  {% for event in events %}
			  <a href="{% url 'earth:event_info' event.id %}" class="list-group-item"><i class="fa fa-calendar"></i> {{ event.name }}</a>
			  {% endfor %}
			  {% for thread in threads %}
			  <a href="{% url 'earth:thread_info' thread.id %}" class="list-group-item"><i class="fa fa-file-text"></i> {{ thread.title }}</a>
			  {% endfor %}
			</ul>
		</div>
	</div>

</div>
<div class="col-md-8" style="padding-top: 15px">
	<div class="row">
		<h3>News for You:</h3>

		{% for article in articles %}
		
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="media">
				  <div class="media-left media-middle">
				    <a href="#">
				      <img class="media-object" src="/static/images/news64.png" alt="...">
				    </a>
				  </div>
				  <div class="media-body">
				    <a href="{{ article.url }}" target="_blank"><h4 class="media-heading">{{ article.title }}</h4></a>
				    {{ article.content }}
				  </div>
				</div>
			</div>
		</div>

		{% endfor %}

		
<div>


{% endblock content %}

clubEarth/earth/templates/news_list.html
{% extends 'base.html' %}
{% block title %}
News
{% endblock title %}
{% block content %}
<h1>News:</h1>


{% endblock content %}

clubEarth/earth/templates/thread_info.html
{% extends 'base.html' %}
{% block title %}
{{thread.title}}
{% endblock title %}
{% block content %}

<h1>{{ thread.title }}<small> by: {{ thread.author }} <br /> Rochester, NY <i class="fa fa-location-arrow"></i></small></h1>

<script type="text/javascript">
	$('#newcomment').on('shown.bs.modal', function () {
	  $('input[name="content"]').focus()
	})
</script>

<br />
<hr />
<ol class="breadcrumb">
	<li><a href="/forums">Forums</a></li>
	<li><a href="{% url 'earth:forum_category' thread.category.id %}"> {{ thread.category.name }}</a></li>
	<li class="active">{{ thread.title }}</li>
</ol>

<div class="panel panel-default">
	<div class="panel-heading"> {{ thread.author }} on {{ thread.date }} </div>
	<div class="panel-body">
		{{ thread.content }}
	</div>
</div>


{% for comment in comments %}
<div class="panel panel-default">
	<div class="panel-heading"> {{ comment.author }} on {{ comment.date }} </div>
	<div class="panel-body">
		{{ comment.content }}
	</div>
</div>
{% endfor %}

  <form action="{% url 'earth:thread_info' thread.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="content">Comment</label>
            {{ comment_form.content }}
        </div>    
        <div class="form-group">
          <button type="submit" class="btn btn-default pull-right">Submit</button>
        </div>
  </form>






{% endblock content %}